name: csmp-search-engine

services:
  fastapi_service:
    build:
      context: ./services/fastapi_service
      dockerfile: Dockerfile
    container_name: fastapi-backend-service
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - csmp-network

  # streamlit_service:
  #   build:
  #     context: ./services/streamlit_service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8501:8501"
  #   networks:
  #     - csmp-network

  # triton_service:
  #   build:
  #     context: ./services/triton_service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8001:8001"
  #   networks:
  #     - csmp-network

  # postgres_service:
  #   image: pgvector/pgvector:pg16
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pg_data:/var/lib/postgresql/data
  #   networks:
  #     - csmp-network

networks:
  csmp-network:
    driver: bridge

# volumes:
#   pg_data:
